# -*- coding: utf-8 -*-
"""preprocessing_data_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKssfqYclEhoaCBjtilvTkL6xF3b2Nyt
"""

from google.colab import files
import pandas as pd
import random

# -----------------------------
# Upload dataset
# -----------------------------

uploaded = files.upload()

# -----------------------------
# Load dataset
# -----------------------------

df = pd.read_csv("budgetwise_finance_dataset_original.csv")

# -----------------------------
# Fill missing values
# -----------------------------

df["payment_mode"] = df["payment_mode"].fillna("Unknown")
df["location"] = df["location"].fillna("Unknown")
df["notes"] = df["notes"].fillna("")

# -----------------------------
# Clean category names
# -----------------------------

df["category"] = df["category"].astype(str).str.strip().str.lower()

category_map = {

    "food":"food",
    "foods":"food",
    "foodd":"food",
    "fod":"food",

    "rent":"rent",
    "rentt":"rent",
    "rnt":"rent",

    "travel":"travel",
    "travl":"travel",
    "traval":"travel",

    "education":"education",
    "educaton":"education",
    "edu":"education",

    "entertainment":"entertainment",
    "entertain":"entertainment",
    "entrtnmnt":"entertainment",

    "utilities":"utilities",
    "utility":"utilities",
    "utilties":"utilities",
    "utlities":"utilities",

    "health":"health",
    "helth":"health",

    "saving":"savings",
    "savings":"savings",

    "others":"others",
    "other":"others",
    "misc":"others",

    "salary":"salary",
    "bonus":"bonus",
    "investment":"investment",
    "freelance":"freelance"

}

df["category"] = df["category"].replace(category_map)

# -----------------------------
# Clean payment mode
# -----------------------------

df["payment_mode"] = (
    df["payment_mode"]
    .astype(str)
    .str.strip()
    .str.title()
)

# -----------------------------
# Clean location
# -----------------------------

df["location"] = (
    df["location"]
    .astype(str)
    .str.strip()
    .str.title()
)

# -----------------------------
# Description dictionary
# -----------------------------

description_dict = {

    "food":[
        "Swiggy order",
        "Zomato order",
        "Restaurant dinner",
        "Cafe breakfast",
        "Dominos pizza",
        "Burger King meal",
        "Lunch at restaurant",
        "Food delivery",
        "Starbucks coffee",
        "Family dinner"
    ],

    "travel":[
        "Uber ride",
        "Ola cab",
        "Metro recharge",
        "Bus ticket",
        "Train ticket",
        "Flight booking",
        "Fuel payment",
        "Taxi fare",
        "Airport transfer",
        "Travel expense"
    ],

    "rent":[
        "Monthly house rent",
        "Apartment rent",
        "PG rent",
        "Room rent",
        "Rental payment",
        "Flat rent",
        "Accommodation rent",
        "Home rent",
        "Lease payment",
        "Rent transfer"
    ],

    "utilities":[
        "Electricity bill",
        "Water bill",
        "Gas bill",
        "Internet bill",
        "WiFi recharge",
        "Mobile recharge",
        "Broadband bill",
        "Utility payment",
        "Power bill",
        "EB payment"
    ],

    "entertainment":[
        "Netflix subscription",
        "Movie ticket",
        "Spotify premium",
        "Amazon Prime",
        "Disney Plus",
        "Gaming subscription",
        "Concert ticket",
        "Weekend movie",
        "Theatre booking",
        "OTT subscription"
    ],

    "education":[
        "College fees",
        "School fees",
        "Book purchase",
        "Online course",
        "Udemy course",
        "Exam fees",
        "Library fees",
        "Tuition fees",
        "Training program",
        "Educational material"
    ],

    "health":[
        "Doctor consultation",
        "Pharmacy purchase",
        "Hospital bill",
        "Medical test",
        "Medicine purchase",
        "Health insurance",
        "Clinic visit",
        "Dental treatment",
        "Blood test",
        "Health checkup"
    ],

    "salary":[
        "Monthly salary",
        "Salary credit",
        "Company payroll",
        "Salary received",
        "Payroll deposit"
    ],

    "bonus":[
        "Annual bonus",
        "Performance bonus",
        "Festival bonus",
        "Incentive received"
    ],

    "investment":[
        "Mutual fund investment",
        "Stock purchase",
        "SIP investment",
        "Investment deposit",
        "Equity investment"
    ],

    "freelance":[
        "Freelance project",
        "Client payment",
        "Consulting income",
        "Website project",
        "Freelance earnings"
    ],

    "savings":[
        "Savings deposit",
        "Transfer to savings",
        "Emergency fund",
        "Savings account deposit",
        "Monthly savings"
    ],

    "others":[
        "General expense",
        "Miscellaneous purchase",
        "Other payment",
        "Cash withdrawal",
        "Misc expense"
    ]

}

# -----------------------------
# Generate realistic notes
# -----------------------------

new_notes = []

for cat in df["category"]:

    if cat in description_dict:
        new_notes.append(random.choice(description_dict[cat]))
    else:
        new_notes.append("General transaction")

df["notes"] = new_notes

# -----------------------------
# Remove duplicates
# -----------------------------

df = df.drop_duplicates()

# -----------------------------
# Reset index
# -----------------------------

df = df.reset_index(drop=True)

# -----------------------------
# Save cleaned dataset
# -----------------------------

df.to_csv(
    "cleaned_budgetwise_dataset.csv",
    index=False
)

print("Dataset cleaned successfully!")

print()

print(df["category"].value_counts())

print()

print(df.head())

# -----------------------------
# Download
# -----------------------------

files.download("cleaned_budgetwise_dataset.csv")