# -*- coding: utf-8 -*-
"""test_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ws3jiygNJnd4IfBGzpxB1PftjlfZv5MD
"""

from database import client

try:
    client.admin.command("ping")
    print("✅ Connected to Local MongoDB Successfully!")
except Exception as e:
    print("❌ Connection Failed")
    print(e)