# -*- coding: utf-8 -*-
"""compare_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHMGlsMaIRYC5N2GcnPxHb82zZdhi-em
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score

# =====================================
# Load Dataset
# =====================================

df = pd.read_csv("../dataset/budgetwise_finance_dataset.csv")

# =====================================
# Handle Missing Values
# =====================================

df["notes"] = df["notes"].fillna("")
df["payment_mode"] = df["payment_mode"].fillna("")
df["location"] = df["location"].fillna("")
df["category"] = df["category"].fillna("unknown")

# =====================================
# Create Text Feature
# =====================================

df["text"] = (
    df["notes"].astype(str)
    + " "
    + df["payment_mode"].astype(str)
    + " "
    + df["location"].astype(str)
)

# =====================================
# Remove Remaining Missing Values
# =====================================

df = df.dropna(subset=["text", "category"])

# =====================================
# Debug Checks
# =====================================

print("\nDataset Shape:", df.shape)

print("\nMissing Values:")
print(df[["text", "category"]].isnull().sum())

# =====================================
# Features and Target
# =====================================

X = df["text"]
y = df["category"]

# =====================================
# Train Test Split
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# =====================================
# Models
# =====================================

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Multinomial Naive Bayes": MultinomialNB(),
    "Linear SVC": LinearSVC()
}

print("\n==============================")
print("MODEL COMPARISON")
print("==============================\n")

# =====================================
# Train and Compare
# =====================================

for name, classifier in models.items():

    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(stop_words="english")),
        ("classifier", classifier)
    ])

    pipeline.fit(X_train, y_train)

    predictions = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)

    print(f"{name}: {accuracy:.4f}")

print("\nComparison Complete!")