# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oi77hvi0z57Wi8XjngKrH85bO-Tw6IWV
"""

import joblib

# Load trained model
model = joblib.load("../saved_models/expense_classifier.pkl")

print("LinearSVC Model Loaded Successfully!\n")

while True:

    notes = input("Enter transaction description: ")
    payment = input("Enter payment mode: ")
    location = input("Enter location: ")

    text = notes + " " + payment + " " + location

    prediction = model.predict([text])

    print("\nPredicted Category:", prediction[0])

    again = input("\nTest another transaction? (y/n): ")

    if again.lower() != "y":
        print("\nExiting...")
        break
