# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysErmMmnqpmtISdSfM7u40l7hSsEBiH0
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# =====================================
# Load Dataset
# =====================================

df = pd.read_csv("../dataset/budgetwise_finance_dataset.csv")

# =====================================
# Handle Missing Values
# =====================================

df["notes"] = df["notes"].fillna("")
df["payment_mode"] = df["payment_mode"].fillna("")
df["location"] = df["location"].fillna("")
df["category"] = df["category"].fillna("unknown")

# =====================================
# Create Text Feature
# =====================================

df["text"] = (
    df["notes"].astype(str)
    + " "
    + df["payment_mode"].astype(str)
    + " "
    + df["location"].astype(str)
)

# =====================================
# Remove Remaining Missing Values
# =====================================

df = df.dropna(subset=["text", "category"])

# =====================================
# Input and Target
# =====================================

X = df["text"]
y = df["category"]

# =====================================
# Train-Test Split
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# =====================================
# Build Pipeline
# =====================================

model = Pipeline([
    ("tfidf", TfidfVectorizer(stop_words="english")),
    ("classifier", LinearSVC())
])

# =====================================
# Train Model
# =====================================

print("Training LinearSVC Model...")

model.fit(X_train, y_train)

print("Training Completed!")

# =====================================
# Prediction
# =====================================

predictions = model.predict(X_test)

# =====================================
# Evaluation
# =====================================

accuracy = accuracy_score(y_test, predictions)

print("\nAccuracy:")
print(round(accuracy, 4))

print("\nClassification Report:")
print(classification_report(y_test, predictions))

# =====================================
# Save Model
# =====================================

joblib.dump(model, "../saved_models/expense_classifier.pkl")

print("\nModel saved successfully!")